spring:
  profiles:
    active: dev
---
spring:
  application:
    name: microcloud-config-eureka-server
  profiles: dev
# 安全认证
security:
  basic:
    enabled: true # 开启安全认证模式
  user:
    name: eurekadev
    password: 123

eureka:
  client: # 客户端注册Eureka注册的配置
    service-url:
      defaultZone: http://eurekadev:123@eureka-7001.com:7001/eureka
    register-with-eureka: false # eureka服务本身不注册至eureka内
    fetch-registry: false   # 不通过eureka获取注册信息
  instance: # eureak实例定义
    hostname: eureka-7001.com # 追加Eureka实例所在的主机名称
server:
  port: 7001
---
spring:
  application:
    name: microcloud-config-eureka-server
  profiles: beta
# 安全认证
security:
  basic:
    enabled: true # 开启安全认证模式
  user:
    name: eurekabeta
    password: 123

eureka:
  client: # 客户端注册Eureka注册的配置
    service-url:
      defaultZone: http://eurekabeta:123@eureka-7001.com:7001/eureka
    register-with-eureka: false # eureka服务本身不注册至eureka内
    fetch-registry: false   # 不通过eureka获取注册信息
  instance: # eureak实例定义
    hostname: eureka-7001.com # 追加Eureka实例所在的主机名称
server:
  port: 7001
