spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: microconfig-test-dev
---
spring:
  profiles: default
  application:
    name: microconfig-test-default
---
spring:
  profiles: beta
  application:
    name: microconfig-test-beta

